#!/usr/bin/env python3
"""
Checkpoint Conversion Script
Convert Agent Lightning / VERL trained checkpoint to HuggingFace format.

Features:
  - Supports auto-loading checkpoint path from training script output
  - Supports manual specification of checkpoint and output paths
  - Auto-detects safetensors / bin / pt formats
"""

import os
import sys
import torch
import glob
import argparse
from transformers import AutoModelForCausalLM, AutoTokenizer
from safetensors.torch import load_file


def get_default_checkpoint_path():
    """
    Automatically get the latest checkpoint path.
    
    Priority:
    1. Read from last_checkpoint.txt (auto-generated by training script)
    2. Scan checkpoints directory for latest global_step_*
    """
    # Method 1: Read from training script generated file
    checkpoint_info_file = "last_checkpoint.txt"
    if os.path.exists(checkpoint_info_file):
        with open(checkpoint_info_file, "r") as f:
            path = f.read().strip()
            if os.path.exists(path):
                print(f"Reading checkpoint path from {checkpoint_info_file}")
                return path
            else:
                print(f"Warning: Path in {checkpoint_info_file} does not exist: {path}")
    
    # Method 2: Scan checkpoints directory
    checkpoint_base = os.path.join("checkpoints", "AgentLightningTutorial")
    if os.path.exists(checkpoint_base):
        experiments = [d for d in os.listdir(checkpoint_base) 
                      if os.path.isdir(os.path.join(checkpoint_base, d))]
        if experiments:
            # Get the most recent experiment directory
            experiments.sort(key=lambda x: os.path.getmtime(os.path.join(checkpoint_base, x)), reverse=True)
            exp_dir = os.path.join(checkpoint_base, experiments[0])
            
            # Find the largest global_step
            steps = [d for d in os.listdir(exp_dir) if d.startswith("global_step_")]
            if steps:
                steps.sort(key=lambda x: int(x.split("_")[-1]), reverse=True)
                checkpoint_path = os.path.join(exp_dir, steps[0], "actor", "huggingface")
                if os.path.exists(checkpoint_path):
                    print(f"Auto-detected latest checkpoint: {checkpoint_path}")
                    return checkpoint_path
    
    return None


def convert_checkpoint(checkpoint_path, output_path, base_model_path):
    """
    Convert checkpoint to HuggingFace format.
    
    Args:
        checkpoint_path: VERL output checkpoint directory
        output_path: Path to save converted model
        base_model_path: Base model path (for loading model structure)
    """
    print("=" * 70)
    print("Starting Checkpoint Conversion")
    print("=" * 70)
    print(f"  Base Model: {base_model_path}")
    print(f"  Checkpoint: {checkpoint_path}")
    print(f"  Output Path: {output_path}")

    # 1. Load Tokenizer
    print("\nLoading Tokenizer...")
    try:
        tokenizer = AutoTokenizer.from_pretrained(
            os.path.join(checkpoint_path, "huggingface"), 
            trust_remote_code=True
        )
    except:
        try:
            tokenizer = AutoTokenizer.from_pretrained(checkpoint_path, trust_remote_code=True)
        except:
            print("   Warning: Could not load tokenizer from checkpoint, using base model...")
            tokenizer = AutoTokenizer.from_pretrained(base_model_path, trust_remote_code=True)
    
    # 2. Load Checkpoint Weights
    print("\nLoading checkpoint weights...")
    state_dict = {}

    # Try safetensors format
    safetensor_files = glob.glob(os.path.join(checkpoint_path, "*.safetensors"))
    if safetensor_files:
        print(f"   Found {len(safetensor_files)} safetensors files")
        for f in safetensor_files:
            print(f"   Loading {os.path.basename(f)}...")
            state_dict.update(load_file(f))
    else:
        # Try bin format
        bin_files = glob.glob(os.path.join(checkpoint_path, "*.bin"))
        if bin_files:
            print(f"   Found {len(bin_files)} bin files")
            for f in bin_files:
                print(f"   Loading {os.path.basename(f)}...")
                state_dict.update(torch.load(f, map_location="cpu"))
        else:
            # Try pt format (VERL/FSDP output)
            pt_files = glob.glob(os.path.join(checkpoint_path, "*.pt"))
            if pt_files:
                print(f"   Found {len(pt_files)} pt files")
                for f in pt_files:
                    if "optim" in f or "extra_state" in f: 
                        continue
                    print(f"   Loading {os.path.basename(f)}...")
                    state_dict.update(torch.load(f, map_location="cpu"))
            else:
                print("Error: No valid checkpoint files found (.safetensors/.bin/.pt)")
                sys.exit(1)

    # 3. Filter Internal Keys
    print("\nFiltering internal keys...")
    new_state_dict = {}
    removed_keys = []
    for k, v in state_dict.items():
        if "_snapshot" in k or "optimizer" in k:
            removed_keys.append(k)
        else:
            new_state_dict[k] = v

    print(f"   Removed {len(removed_keys)} internal keys")

    # 4. Load Base Model Structure
    print("\nLoading base model structure...")
    try:
        model = AutoModelForCausalLM.from_pretrained(
            base_model_path,
            trust_remote_code=True,
            device_map="cpu",
            torch_dtype=torch.float16,
            local_files_only=True
        )
        print("   Loaded from local cache")
    except Exception as e:
        print(f"   Local cache not found, downloading...")
        model = AutoModelForCausalLM.from_pretrained(
            base_model_path,
            trust_remote_code=True,
            device_map="cpu",
            torch_dtype=torch.float16
        )

    # 5. Apply Weights
    print("\nApplying trained weights to model...")
    missing, unexpected = model.load_state_dict(new_state_dict, strict=False)

    if missing:
        print(f"   Warning: Missing keys: {len(missing)}")
    if unexpected:
        print(f"   Warning: Unexpected keys: {len(unexpected)}")

    # 6. Save Converted Model
    print(f"\nSaving converted model to {output_path}...")
    os.makedirs(output_path, exist_ok=True)
    model.save_pretrained(output_path)
    tokenizer.save_pretrained(output_path)

    print("\n" + "=" * 70)
    print("Conversion Complete!")
    print("=" * 70)
    print(f"\nModel saved to: {output_path}")
    
    # Save converted model path for downstream scripts
    converted_model_file = "last_converted_model.txt"
    with open(converted_model_file, "w") as f:
        f.write(os.path.abspath(output_path))
    print(f"Model path saved to: {converted_model_file}")


def parse_args():
    """Parse command-line arguments"""
    parser = argparse.ArgumentParser(
        description="Convert VERL checkpoint to HuggingFace format",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    parser.add_argument(
        "--checkpoint_path", type=str, default=None,
        help="Checkpoint directory path (leave empty for auto-detection)"
    )
    parser.add_argument(
        "--output_path", type=str, default=None,
        help="Output directory path (leave empty to use ./converted_model)"
    )
    parser.add_argument(
        "--base_model", type=str, default="Qwen/Qwen2.5-3B-Instruct",
        help="Base model path or HuggingFace ID"
    )
    
    return parser.parse_args()


def main():
    args = parse_args()
    
    # Get checkpoint path
    checkpoint_path = args.checkpoint_path
    if checkpoint_path is None:
        checkpoint_path = get_default_checkpoint_path()
        if checkpoint_path is None:
            print("Error: Cannot auto-detect checkpoint path")
            print("   Please use --checkpoint_path to specify")
            print("\nUsage example:")
            print("   python convert_checkpoint.py --checkpoint_path checkpoints/.../huggingface")
            sys.exit(1)
    
    # Set output path
    output_path = args.output_path
    if output_path is None:
        output_path = "./converted_model"
    
    # Verify checkpoint path exists
    if not os.path.exists(checkpoint_path):
        print(f"Error: Checkpoint path does not exist: {checkpoint_path}")
        sys.exit(1)
    
    convert_checkpoint(checkpoint_path, output_path, args.base_model)


if __name__ == "__main__":
    main()
