import hydra
from omegaconf import DictConfig, OmegaConf
import os

# Define the configuration structure
config = {
    "data": {
        "train_files": "/root/agent-lightning/data/train.parquet",
        "val_files": "/root/agent-lightning/data/test.parquet",
        "prompt_key": "prompt",
        "reward_fn_key": "data_source",  # Using data_source as a dummy reward key
        "train_batch_size": 2,  # Reduced for 24GB VRAM
        "val_batch_size": None,
        "max_prompt_length": 512,
        "max_response_length": 256,
        "return_raw_chat": False,
        "return_raw_input_ids": False,
        "return_multi_modal_inputs": True,
        "truncation": "error",
        "shuffle": True,
        "validation_shuffle": False,
        "filter_overlong_prompts": False,
        "filter_overlong_prompts_workers": 1,
        "dataloader_num_workers": 8,
        "image_key": "images",
        "video_key": "videos",
        "custom_cls": {"name": None, "path": None},
        "datagen": {"name": None, "path": None},
        "sampler": {"class_name": None, "class_path": None},
        "tokenizer": None,
        "trust_remote_code": False,
        "use_shm": False,
        "return_full_prompt": False,
    },
    "actor_rollout_ref": {
        "hybrid_engine": True,
        "model": {
            "path": "Qwen/Qwen2.5-0.5B-Instruct",
            "tokenizer_path": "Qwen/Qwen2.5-0.5B-Instruct",
            "trust_remote_code": False,
            "use_remove_padding": True,
            "use_shm": False,
            "enable_gradient_checkpointing": True,
            "enable_activation_offload": False,
            "lora_rank": 0,
            "lora_alpha": 16,
            "target_modules": "all-linear",
            "use_fused_kernels": False,
            "fused_kernel_options": {"impl_backend": "torch"},
            "use_liger": False,
            "override_config": {"attn_implementation": "eager"},
            "external_lib": None,
            "exclude_modules": None,
            "custom_chat_template": None,
        },
        "rollout": {
            "name": "vllm",
            "temperature": 1.0,
            "top_k": -1,
            "top_p": 1,
            "prompt_length": 512,
            "response_length": 256,
            "dtype": "bfloat16",
            "gpu_memory_utilization": 0.1,  # Drastically reduced for 24GB VRAM
            "ignore_eos": False,
            "enforce_eager": True,
            "free_cache_engine": True,
            "load_format": "dummy_dtensor",
            "tensor_model_parallel_size": 1,
            "max_num_batched_tokens": 8192,
            "max_num_seqs": 1024,
            "log_prob_micro_batch_size": None,
            "log_prob_micro_batch_size_per_gpu": 1, # Explicitly set to 1 to fix validation error
            "log_prob_max_token_len_per_gpu": 16384,
            "log_prob_use_dynamic_bsz": False,
            "disable_log_stats": True,
            "enable_chunked_prefill": True,
            "n": 2,  # Reduced rollout_n
            "do_sample": True,
            "mode": "async",
            "agent": {
                "num_workers": 8,
                "agent_loop_config_path": None,
                "custom_async_server": {
                    "name": "PatchedvLLMServer",
                    "path": "pkg://agentlightning.verl.async_server",
                },
            },
            "engine_kwargs": {
                "vllm": {"swap_space": None, "disable_mm_preprocessor_cache": False},
                "sglang": {"attention_backend": None},
            },
            "val_kwargs": {
                "n": 1,
                "temperature": 0,
                "top_p": 1.0,
                "top_k": -1,
                "do_sample": False,
            },
            "multi_turn": {
                "enable": False,
                "max_user_turns": None,
                "max_assistant_turns": None,
                "interaction_config_path": None,
                "tool_config_path": None,
                "use_inference_chat_template": False,
                "max_tool_response_length": 256,
                "tool_response_truncate_side": "middle",
                "max_parallel_calls": 1,
                "tokenization_sanity_check_mode": "strict",
                "format": "hermes",
                "completion_callback": None,
            },
            "trace": {"token2text": False, "backend": None},
            "update_weights_bucket_megabytes": 512,
            "layered_summon": False,
            "multi_stage_wake_up": False,
            "calculate_log_probs": False,
            "max_model_len": None,
        },
        "ref": {
            "fsdp_config": {
                "wrap_policy": {"min_num_params": 0},
                "param_offload": True,  # Offload reference model
                "optimizer_offload": False,
                "fsdp_size": -1,
                "reshard_after_forward": True,
                "forward_prefetch": False,
            },
            "strategy": "fsdp",
            "log_prob_micro_batch_size": None,
            "log_prob_micro_batch_size_per_gpu": 1,
            "log_prob_max_token_len_per_gpu": 16384,
            "log_prob_use_dynamic_bsz": False,
            "ulysses_sequence_parallel_size": 1,
            "use_torch_compile": True,
            "entropy_checkpointing": False,
            "entropy_from_logits_with_chunking": False,
        },
        "actor": {
            "strategy": "fsdp",
            "ppo_mini_batch_size": 1,  # Reduced
            "ppo_micro_batch_size": None,
            "ppo_micro_batch_size_per_gpu": 1,  # Reduced
            "use_dynamic_bsz": False,
            "ppo_max_token_len_per_gpu": 16384,
            "grad_clip": 1.0,
            "clip_ratio": 0.2,
            "entropy_coeff": 0,
            "ppo_epochs": 1,
            "shuffle": False,
            "optim": {
                "lr": 1e-6,
                "lr_warmup_steps_ratio": 0.0,
                "min_lr_ratio": 0.0,
                "warmup_style": "constant",
                "total_training_steps": -1,
                "weight_decay": 0.01,
                "lr_warmup_steps": -1,
                "num_cycles": 0.5,
            },
            "fsdp_config": {
                "wrap_policy": {"min_num_params": 0},
                "param_offload": True,  # Offload actor model
                "optimizer_offload": True,  # Offload actor optimizer
                "fsdp_size": -1,
                "reshard_after_forward": True,
                "forward_prefetch": False,
                "offload_policy": False,
            },
            "ulysses_sequence_parallel_size": 1,
            "use_kl_loss": False,
            "kl_loss_coef": 0.001,
            "kl_loss_type": "low_var_kl",
            "use_torch_compile": True,
            "entropy_checkpointing": False,
            "entropy_from_logits_with_chunking": False,
            "loss_agg_mode": "token-mean",
            "policy_loss": {
                "loss_mode": "vanilla",
                "ppo_kl_coef": 0.1,
                "clip_cov_ratio": 2e-4,
                "kl_cov_ratio": 2e-4,
                "clip_cov_lb": 1.0,
                "clip_cov_ub": 5.0,
            },
            "clip_ratio_low": 0.2,
            "clip_ratio_high": 0.2,
            "clip_ratio_c": 3.0,
        },
    },
    "critic": {
        "strategy": "fsdp",
        "val_batch_size": None,
        "ppo_mini_batch_size": 1,  # Reduced
        "ppo_micro_batch_size": None,
        "ppo_micro_batch_size_per_gpu": None,
        "use_dynamic_bsz": False,
        "ppo_max_token_len_per_gpu": 32768,
        "forward_micro_batch_size": None,
        "forward_micro_batch_size_per_gpu": None,
        "forward_max_token_len_per_gpu": 32768,
        "grad_clip": 1.0,
        "cliprange_value": 0.5,
        "ppo_epochs": 1,
        "shuffle": False,
        "optim": {
            "lr": 1e-5,
            "lr_warmup_steps_ratio": 0.0,
            "min_lr_ratio": None,
            "warmup_style": "constant",
            "total_training_steps": -1,
            "weight_decay": 0.01,
        },
        "fsdp_config": {
            "wrap_policy": {"min_num_params": 0},
            "param_offload": True,  # Offload critic model
            "optimizer_offload": True,  # Offload critic optimizer
            "fsdp_size": -1,
            "reshard_after_forward": True,
            "forward_prefetch": False,
            "offload_policy": False,
        },
        "model": {
            "path": "Qwen/Qwen2.5-0.5B-Instruct",
            "tokenizer_path": "Qwen/Qwen2.5-0.5B-Instruct",
            "trust_remote_code": False,
            "use_remove_padding": True,
            "use_shm": False,
            "enable_gradient_checkpointing": True,
            "enable_activation_offload": False,
            "lora_rank": 0,
            "lora_alpha": 16,
            "target_modules": "all-linear",
            "override_config": {"attn_implementation": "eager"},
            "external_lib": None,
        },
        "ulysses_sequence_parallel_size": 1,
        "loss_agg_mode": "token-mean",
        "profiler": {
            "ranks": [],
            "discrete": False,
            "all_ranks": False,
            "_target_": "verl.utils.profiler.ProfilerConfig",
        },
        "checkpoint": {
            "save_contents": ["model", "optimizer", "extra"],
            "load_contents": ["model", "optimizer", "extra"],
        },
        "rollout_n": 2,
        "_target_": "verl.trainer.config.FSDPCriticConfig",
    },
    "reward_model": {
        "enable": False,
        "strategy": "fsdp",
        "micro_batch_size": None,
        "micro_batch_size_per_gpu": None,
        "forward_max_token_len_per_gpu": 32768,
        "max_length": None,
        "ulysses_sequence_parallel_size": 1,
        "use_dynamic_bsz": False,
        "fsdp_config": {
            "wrap_policy": {"min_num_params": 0},
            "param_offload": False,
            "fsdp_size": -1,
            "reshard_after_forward": True,
            "forward_prefetch": False,
        },
        "model": {
            "path": "~/models/FsfairX-LLaMA3-RM-v0.1",
            "input_tokenizer": "Qwen/Qwen2.5-0.5B-Instruct",
            "trust_remote_code": False,
            "use_remove_padding": False,
            "use_shm": False,
            "use_fused_kernels": False,
            "external_lib": None,
        },
        "launch_reward_fn_async": False,
        "reward_manager": "naive",
        "sandbox_fusion": {
            "max_concurrent": 64,
            "memory_limit_mb": 1024,
            "url": None,
        },
        "profiler": {
            "ranks": [],
            "discrete": False,
            "all_ranks": False,
            "_target_": "verl.utils.profiler.ProfilerConfig",
        },
    },
    "custom_reward_function": {"name": "compute_score", "path": None},
    "ray_init": {"num_cpus": None, "timeline_json_file": None},
    "algorithm": {
        "gamma": 1.0,
        "lam": 1.0,
        "adv_estimator": "grpo",
        "kl_penalty": "kl",
        "use_kl_in_reward": True,
        "kl_ctrl": {
            "type": "fixed",
            "kl_coef": 0.001,
            "target_kl": 0.1,
            "horizon": 10000,
            "_target_": "verl.trainer.config.KLControlConfig",
        },
        "use_pf_ppo": False,
        "pf_ppo": {
            "weight_pow": 2.0,
            "reweight_method": "pow",
            "_target_": "verl.trainer.config.PFPPOConfig",
        },
        "norm_adv_by_std_in_grpo": True,
        "_target_": "verl.trainer.config.AlgoConfig",
    },
    "trainer": {
        "strategy": "fsdp",
        "total_training_steps": 50,  # Small number for verification
        "total_epochs": 1,
        "save_freq": 20,
        "test_freq": 20,
        "project_name": "AgentLightningTutorial",
        "experiment_name": "math_agent_0.5b_a10_v1",
        "logger": ["console"],
        "val_before_train": False,
        "val_only": False,
        "resume_mode": "auto",
        "resume_from_path": None,
        "nnodes": 1,
        "n_gpus_per_node": 1,
        "default_local_dir": "checkpoints/AgentLightningTutorial/math_agent_0.5b_a10_v1",
        "default_hdfs_dir": None,
        "del_local_ckpt_after_load": False,
        "rollout_data_dir": None,
        "validation_data_dir": None,
        "balance_batch": True,
        "critic_warmup": 0,
        "log_val_generations": 0,
        "device": "cuda",
        "max_actor_ckpt_to_keep": None,
        "max_critic_ckpt_to_keep": None,
        "use_legacy_worker_impl": "auto",
        "ray_wait_register_center_timeout": 300,
        "esi_redundant_time": 0,
        "profile_steps": None,
        "npu_profile": {
            "options": {
                "save_path": "./profiler_data",
                "with_stack": False,
                "with_memory": False,
                "record_shapes": False,
                "with_cpu": True,
                "with_npu": True,
                "with_module": False,
                "level": "level1",
                "analysis": True,
            }
        },
        "worker_nsight_options": {
            "trace": "cuda,nvtx,cublas,ucx",
            "cuda-graph-trace": "graph",
            "cuda-memory-usage": "true",
            "capture-range": "cudaProfilerApi",
            "capture-range-end": None,
            "kill": "none",
        },
        "controller_nsight_options": {
            "trace": "cuda,nvtx,cublas,ucx",
            "cuda-graph-trace": "graph",
            "cuda-memory-usage": "true",
        },
    },
}

def main():
    # Convert dictionary to DictConfig
    cfg = OmegaConf.create(config)
    
    # Import the run_ppo function
    from agentlightning.verl.entrypoint import run_ppo
    
    # Run PPO
    run_ppo(cfg, train_dataset=None, val_dataset=None, store=None, llm_proxy=None, adapter=None)

if __name__ == "__main__":
    main()
